# Change these first 
owner: shinesystems # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Shine Systems Web Server
    url: https://www.shinesystems.co.uk
  - name: Hosted Email Server
    url: https://mail.shinesystems.co.uk
  - name: Email Filtering Appliance
    url: https://efa1.shinesystems.co.uk
  - name: Internet-UK Email
    url: https://mail.internet-uk.net
  - name: Phil Personal Website
    url: https://m0vse.uk
  - name: wfview Website
    url: https://wfview.org
  - name: wfview Forum
    url: https://forum.wfview.org
  - name: LRS Website
    url: https://g3lrs.org.uk
  - name: LRG Website
    url: https://lrg.org.uk
  - name: Falcon Players Website
    url: https://falconplayers.org
  - name: SPC Website
    url: https://spc-hvac.co.uk    
  - name: Copperad Website
    url: https://copperad.co.uk
  - name: Rosemary Conley Website
    url: https://rosemaryconley.com
  - name: Mace Bearer Website
    url: https://macebearer.com
  - name: Facial Flex Website
    url: https://facial-flex.co.uk
  - name: TP Website
    url: https://total-precision.co.uk    
  - name: Villa Vermonte Website
    url: https://www.villavermonte.com    
  - name: RNARS Website
    url: https://www.rnars.org.uk    
  - name: Villa Vermonte Website
    url: https://www.villavermonte.com    
  - name: Regency Cars Website
    url: https://www.regency-cars.com    
  - name: Scanner Software Website
    url: https://www.scannersoftware.co.uk    
  - name: Taylor Website
    url: https://www.taylor.org.uk    
  - name: A1 Steel Website
    url: https://www.a1steel.co.uk    
    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.shinesystems.co.uk
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
